### ISSUE TITLE
AMO and addon signing drama

### ISSUE THREAD

**Issue by gear54rus** [oa-platform/RESTClient-APS#32]
Reports are coming in that FF42+ will have some dumb feature which prevents unsigned addons:

https://news.ycombinator.com/item?id=10038999

Need to find a way to break free of this attempt to make ecosystem closed.

I've never had any experience with this addon signing thing, so **any help is greatly appreciated**!

**Comment by mastacheata** [comment]
FF starts warning about unsigned addons in 40, and will start disabling unsigned addons by default in 41 before it will be mandatory (i.e. you can't turn off signature checks) in 42

Here's the official documentation page with all the infos on when this will take effect and who can avoid it:
https://wiki.mozilla.org/Addons/Extension_Signing

And this is the de-facto guide about code signing an XPI file on windows (and linux is linked from there): https://developer.mozilla.org/en-US/docs/Signing_a_XPI

**Comment by gear54rus** [comment]
Hello Benedikt, 

Good to hear from you again :)

I kinda skimmed those docs you linked before opening this and it seems that here is the relevant part in the first link (click to enlarge):

![1](https://cloud.githubusercontent.com/assets/8073599/9323072/1a23daf4-459e-11e5-9107-96da3904e668.png)

And the second part just shows how we can **self-sign** the addon (which still won't allow us to install it everywhere since the CA used in the process is not trusted).

With all that in mind, as I understand it, the addon (this addon in this case) will have to pass some *blackbox* review from Mozilla to be admitted into mainstream versions of Firefox - even if we don't host it on AMO. This pisses me off to no end :(

Did I understand the process correctly?

**Comment by mastacheata** [comment]
As far as I understand, the only requirement so far is a valid signature (you get that automatically if you give your source code to AMO and check the "do not publish" box). 
Only if that doesn't work for whatever reason you need to get a human at Mozilla to check your code and sign it for you. 

In the future there might be more requirements to get the highly anticipated signature, but considering how long the discussion about signing at all took, we won't live to see that any more (I'm younger than 30 and still doubt to see that)

**Comment by gear54rus** [comment]
Ok then, in scope of this issue I'll dig the second link and try self-signing a build... Thanks a ton!

**Comment by gear54rus** [comment]
Also, it seems that singed/not signed is indicated here (for reference):

![2](https://cloud.githubusercontent.com/assets/8073599/9326521/1ee44844-45bc-11e5-8ab8-b9c963f7ce6d.png)

**Comment by gear54rus** [comment]
FF 43 users report problems... And I still can't get around to this.

Set `xpinstall.signatures.required` to `false` to fix on user's side.

**Comment by gear54rus** [comment]
This latest commit passes validation with 0 errors and 50 warnings when built.
