### ISSUE TITLE
Нужно подписать дополнение

### ISSUE THREAD

**Issue by burashka** [oa-platform/RESTClient-APS#33]
Новый FF выключает дополнение, т.к. оно не подписано.
![_081](https://cloud.githubusercontent.com/assets/2195887/12091504/961c26a2-b308-11e5-90f3-e1924c5bd4c0.png)
Нужно подписать. Помощь: https://developer.mozilla.org/en-US/Add-ons/Distribution

**Comment by gear54rus** [comment]
Hello,

Handled in #32. Please download the [latest release](https://github.com/oa-platform/RESTClient-APS/releases/tag/v1.5).
