### ISSUE TITLE
restclient.sqlite.db is null

### ISSUE THREAD

**Issue by mastacheata** [oa-platform/RESTClient-APS#34]
Haven't used your RestClient in a while, but had to reinstall my computer and upgraded to the latest version now.
It looks like I have problems with the storage for your extension.
The sqlite database file is not there or corrupted.
Problem appears right at the initialization phase where it tries to open the sqlite db.
In that open function I run into an Exception on line 87 of restclient.sqlite.js:
The exception message is: 
    Component returned failure code: 0x8052000b (NS_ERROR_FILE_CORRUPTED) [mozIStorageService.openDatabase]

StackOverflow hints at a problem with my profile's SQLITE DB being corrupted, but it could just as well be the sqlite db shipping with your extension. As I still got very little to no experience with coding Mozilla extensions I'm here looking for your help once again.

Thanks in advance

**Comment by gear54rus** [comment]
Hi,

Will look into it as soon as I return from a trip (tomorrow or the day after).

**Comment by gear54rus** [comment]
For now what I can say is that RESTClient (both this and original) has an asset in your profile folder:

`C:\Users\1\AppData\Roaming\Mozilla\Firefox\Profiles\ook7q89l.default\restclient.sqlite`

This is an sqlite db that should be created automatically upon installation. If it really is a corruption, you can simply remove that file and re-install the extension.

However, if you have a stable reproduction here (other than corruption), I might be able to fix something in the code for it to go away.

**Comment by mastacheata** [comment]
@gear54rus Thanks for the hint. Indeed, the SQLite file was broken. Tried to open it with a standalone database tool and got a similar response as the exception.

Removing the file and reinstalling the Extension fixed the problem.
Thank you so much for your quick response and even responding while abroad.
